# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build my corne'
on:
  push:
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left","corne_right","settings_reset"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y","CONFIG_ZMK_POINTING=y"]'
      branches: '["zmkfirmware/zmk/v0.3-branch"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
