# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build my corne'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano"]'
      shield: '["corne_left","corne_right","settings_reset"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y","CONFIG_ZMK_SLEEP=y","CONFIG_BT_CTLR_TX_PWR_PLUS_8=y","CONFIG_ZMK_POINTING=y"]'
      branches: '["zmkfirmware/zmk/v0.3-branch"]'
      alphas: '["QWERTY"]'
      nav: '["vi"]'
